# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_has_path <- function(i, j, amat, nodes) {
    .Call(`_phsl_cpp_has_path`, i, j, amat, nodes)
}

deep_copy_NumericVector <- function(original, copy) {
    invisible(.Call(`_phsl_deep_copy_NumericVector`, original, copy))
}

vstruct_apply_cpp <- function(undirMat, vs, nodes, maxp = 8L, debug = FALSE) {
    .Call(`_phsl_vstruct_apply_cpp`, undirMat, vs, nodes, maxp, debug)
}

R_loglik_dnode <- function(target, parents, data, k, debuglevel = 0L) {
    .Call(`_phsl_R_loglik_dnode`, target, parents, data, k, debuglevel)
}

vstruct_apply_hgi <- function(undirMat, reference, nodes, vs, data, delta, reverse = 0L, is_discrete = 1L, k = 0, maxp = 8L, just_delta = FALSE, debug = FALSE) {
    .Call(`_phsl_vstruct_apply_hgi`, undirMat, reference, nodes, vs, data, delta, reverse, is_discrete, k, maxp, just_delta, debug)
}

pdag2dag_cpp <- function(g, nodes, direct_all = FALSE) {
    .Call(`_phsl_pdag2dag_cpp`, g, nodes, direct_all)
}

pdag2dag_greedy <- function(a, d, reference, nodes, data, nscores, is_discrete = 1L, k = 0, maxp = 8L, verbose = FALSE) {
    .Call(`_phsl_pdag2dag_greedy`, a, d, reference, nodes, data, nscores, is_discrete, k, maxp, verbose)
}

apply_cpdag_rules <- function(pdag, nodes, remove_invalid = TRUE, debug = FALSE) {
    .Call(`_phsl_apply_cpdag_rules`, pdag, nodes, remove_invalid, debug)
}

normalize_muti <- function(muti, entropy) {
    .Call(`_phsl_normalize_muti`, muti, entropy)
}

assign_small <- function(D, group, ugroup, sgroup, fraction = 0.05, linkage = 1L) {
    .Call(`_phsl_assign_small`, D, group, ugroup, sgroup, fraction, linkage)
}

vstruct_centered_on <- function(x, arcs, dsep_set, alpha, nodes, debug = FALSE) {
    .Call(`_phsl_vstruct_centered_on`, x, arcs, dsep_set, alpha, nodes, debug)
}

vstruct_count_cpp <- function(p, count, vs, debug = FALSE) {
    invisible(.Call(`_phsl_vstruct_count_cpp`, p, count, vs, debug))
}

vstructs_cpp <- function(amat, vsmat, debug = FALSE) {
    .Call(`_phsl_vstructs_cpp`, amat, vsmat, debug)
}

